<?php

use App\Http\Controllers\Backends\ActivityLogController;
use App\Http\Controllers\Backends\AttendanceSessionController;
use App\Http\Controllers\Backends\CertificateController;
use App\Http\Controllers\Backends\DashboardController;
use App\Http\Controllers\Backends\ExamController;
use App\Http\Controllers\Backends\ExamResultController;
use App\Http\Controllers\Backends\FeeChargeController;
use App\Http\Controllers\Backends\GradeRecordController;
use App\Http\Controllers\Backends\HomeworkAssignmentController;
use App\Http\Controllers\Backends\HomeworkSubmissionController;
use App\Http\Controllers\Backends\LessonPlanController;
use App\Http\Controllers\Backends\LevelController;
use App\Http\Controllers\Backends\NotificationController;
use App\Http\Controllers\Backends\RolePermissionController;
use App\Http\Controllers\Backends\SchoolClassController;
use App\Http\Controllers\Backends\SchoolSettingController;
use App\Http\Controllers\Backends\StudentController;
use App\Http\Controllers\Backends\TeacherController;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;
use Laravel\Fortify\Features;

Route::get('/', function () {
    return Inertia::render('welcome', [
        'canRegister' => Features::enabled(Features::registration()),
    ]);
})->name('home');

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');
});

// ── Admin School Management ──
Route::prefix('admin')->name('admin.')->group(function () {
    Route::get('/', fn () => redirect()->route('dashboard'));
    Route::get('/dashboard', fn () => redirect()->route('dashboard'))->name('dashboard');
    Route::get('/levels', [LevelController::class, 'index'])->name('levels');
    Route::post('/levels', [LevelController::class, 'store'])->name('levels.store');
    Route::put('/levels/{level}', [LevelController::class, 'update'])->name('levels.update');
    Route::delete('/levels/{level}', [LevelController::class, 'destroy'])->name('levels.destroy');
    Route::get('/students', [StudentController::class, 'index'])->name('students');
    Route::get('/students/create', [StudentController::class, 'create'])->name('students.create');
    Route::get('/students/layout', [StudentController::class, 'downloadLayout'])->name('students.layout');
    Route::post('/students/import', [StudentController::class, 'import'])->name('students.import');
    Route::get('/students/export', [StudentController::class, 'export'])->name('students.export');
    Route::post('/students', [StudentController::class, 'store'])->name('students.store');
    Route::get('/students/{student}', [StudentController::class, 'show'])->name('students.show');
    Route::get('/students/{student}/edit', [StudentController::class, 'edit'])->name('students.edit');
    Route::put('/students/{student}', [StudentController::class, 'update'])->name('students.update');
    Route::delete('/students/{student}', [StudentController::class, 'destroy'])->name('students.destroy');
    Route::get('/teachers', [TeacherController::class, 'index'])->name('teachers');
    Route::get('/teachers/layout', [TeacherController::class, 'downloadLayout'])->name('teachers.layout');
    Route::post('/teachers/import', [TeacherController::class, 'import'])->name('teachers.import');
    Route::get('/teachers/export', [TeacherController::class, 'export'])->name('teachers.export');
    Route::get('/teachers/{teacher}/lesson-plans/create', [TeacherController::class, 'createLessonPlan'])->name('teachers.lesson-plans.create');
    Route::post('/teachers/{teacher}/lesson-plans', [TeacherController::class, 'storeLessonPlan'])->name('teachers.lesson-plans.store');
    Route::get('/teachers/{teacher}', [TeacherController::class, 'show'])->name('teachers.show');
    Route::post('/teachers', [TeacherController::class, 'store'])->name('teachers.store');
    Route::put('/teachers/{teacher}', [TeacherController::class, 'update'])->name('teachers.update');
    Route::delete('/teachers/{teacher}', [TeacherController::class, 'destroy'])->name('teachers.destroy');
    Route::get('/classes', [SchoolClassController::class, 'index'])->name('classes');
    Route::post('/classes', [SchoolClassController::class, 'store'])->name('classes.store');
    Route::put('/classes/{schoolClass}', [SchoolClassController::class, 'update'])->name('classes.update');
    Route::delete('/classes/{schoolClass}', [SchoolClassController::class, 'destroy'])->name('classes.destroy');
    Route::get('/attendance/mark', [AttendanceSessionController::class, 'create'])->name('attendance.mark');
    Route::get('/attendance/layout', [AttendanceSessionController::class, 'downloadLayout'])->name('attendance.layout');
    Route::post('/attendance/import', [AttendanceSessionController::class, 'import'])->name('attendance.import');
    Route::get('/attendance/export', [AttendanceSessionController::class, 'export'])->name('attendance.export');
    Route::get('/attendance/{attendanceSession}/edit', [AttendanceSessionController::class, 'edit'])->name('attendance.edit');
    Route::get('/attendance', [AttendanceSessionController::class, 'index'])->name('attendance');
    Route::post('/attendance', [AttendanceSessionController::class, 'store'])->name('attendance.store');
    Route::put('/attendance/{attendanceSession}', [AttendanceSessionController::class, 'update'])->name('attendance.update');
    Route::delete('/attendance/{attendanceSession}', [AttendanceSessionController::class, 'destroy'])->name('attendance.destroy');
    Route::get('/grades', [GradeRecordController::class, 'index'])->name('grades');
    Route::get('/grades/layout', [GradeRecordController::class, 'downloadLayout'])->name('grades.layout');
    Route::post('/grades/import', [GradeRecordController::class, 'import'])->name('grades.import');
    Route::get('/grades/export', [GradeRecordController::class, 'export'])->name('grades.export');
    Route::post('/grades', [GradeRecordController::class, 'store'])->name('grades.store');
    Route::put('/grades/{gradeRecord}', [GradeRecordController::class, 'update'])->name('grades.update');
    Route::delete('/grades/{gradeRecord}', [GradeRecordController::class, 'destroy'])->name('grades.destroy');
    Route::get('/homework', [HomeworkAssignmentController::class, 'index'])->name('homework');
    Route::get('/homework/create', [HomeworkAssignmentController::class, 'create'])->name('homework.create');
    Route::post('/homework', [HomeworkAssignmentController::class, 'store'])->name('homework.store');
    Route::get('/homework/{homeworkAssignment}/edit', [HomeworkAssignmentController::class, 'edit'])->name('homework.edit');
    Route::put('/homework/{homeworkAssignment}', [HomeworkAssignmentController::class, 'update'])->name('homework.update');
    Route::delete('/homework/{homeworkAssignment}', [HomeworkAssignmentController::class, 'destroy'])->name('homework.destroy');
    Route::get('/lesson-plans/create', [LessonPlanController::class, 'create'])->name('lesson-plans.create');
    Route::get('/lesson-plans/{lessonPlan}/edit', [LessonPlanController::class, 'edit'])->name('lesson-plans.edit');
    Route::get('/lesson-plans', [LessonPlanController::class, 'index'])->name('lesson-plans');
    Route::post('/lesson-plans', [LessonPlanController::class, 'store'])->name('lesson-plans.store');
    Route::put('/lesson-plans/{lessonPlan}', [LessonPlanController::class, 'update'])->name('lesson-plans.update');
    Route::delete('/lesson-plans/{lessonPlan}', [LessonPlanController::class, 'destroy'])->name('lesson-plans.destroy');
    Route::get('/homework-submissions', [HomeworkSubmissionController::class, 'index'])->name('homework-submissions');
    Route::post('/homework-submissions', [HomeworkSubmissionController::class, 'store'])->name('homework-submissions.store');
    Route::put('/homework-submissions/{homeworkSubmission}', [HomeworkSubmissionController::class, 'update'])->name('homework-submissions.update');
    Route::delete('/homework-submissions/{homeworkSubmission}', [HomeworkSubmissionController::class, 'destroy'])->name('homework-submissions.destroy');
    Route::get('/fee', [FeeChargeController::class, 'index'])->name('fee');
    Route::get('/fee/create', [FeeChargeController::class, 'create'])->name('fee.create');
    Route::post('/fee', [FeeChargeController::class, 'store'])->name('fee.store');
    Route::get('/fee/{feeCharge}/edit', [FeeChargeController::class, 'edit'])->name('fee.edit');
    Route::put('/fee/{feeCharge}', [FeeChargeController::class, 'update'])->name('fee.update');
    Route::delete('/fee/{feeCharge}', [FeeChargeController::class, 'destroy'])->name('fee.destroy');
    Route::post('/fee/{feeCharge}/payments', [FeeChargeController::class, 'payment'])->name('fee.payments.store');
    Route::get('/exam', [ExamController::class, 'index'])->name('exam');
    Route::post('/exam', [ExamController::class, 'store'])->name('exam.store');
    Route::put('/exam/{exam}', [ExamController::class, 'update'])->name('exam.update');
    Route::delete('/exam/{exam}', [ExamController::class, 'destroy'])->name('exam.destroy');
    Route::get('/exam-results', [ExamResultController::class, 'index'])->name('exam-results');
    Route::post('/exam-results', [ExamResultController::class, 'store'])->name('exam-results.store');
    Route::put('/exam-results/{examResult}', [ExamResultController::class, 'update'])->name('exam-results.update');
    Route::delete('/exam-results/{examResult}', [ExamResultController::class, 'destroy'])->name('exam-results.destroy');
    Route::get('/reports', fn () => Inertia::render('admin/reports/index'))->name('reports');
    Route::get('/certs', [CertificateController::class, 'index'])->name('certs');
    Route::post('/certs', [CertificateController::class, 'store'])->name('certs.store');
    Route::put('/certs/{certificate}', [CertificateController::class, 'update'])->name('certs.update');
    Route::delete('/certs/{certificate}', [CertificateController::class, 'destroy'])->name('certs.destroy');
    Route::get('/honor-roll', fn () => Inertia::render('admin/honor-roll/index'))->name('honor-roll');
    Route::get('/notifications', [NotificationController::class, 'index'])->name('notifications');
    Route::post('/notifications', [NotificationController::class, 'store'])->name('notifications.store');
    Route::put('/notifications/{notification}', [NotificationController::class, 'update'])->name('notifications.update');
    Route::put('/notifications/{notification}/read', [NotificationController::class, 'markRead'])->name('notifications.read');
    Route::put('/notifications-read', [NotificationController::class, 'markAllRead'])->name('notifications.read-all');
    Route::delete('/notifications/{notification}', [NotificationController::class, 'destroy'])->name('notifications.destroy');
    Route::get('/activity-logs', [ActivityLogController::class, 'index'])->name('activity-logs');
    Route::post('/activity-logs', [ActivityLogController::class, 'store'])->name('activity-logs.store');
    Route::put('/activity-logs/{activityLog}', [ActivityLogController::class, 'update'])->name('activity-logs.update');
    Route::delete('/activity-logs/{activityLog}', [ActivityLogController::class, 'destroy'])->name('activity-logs.destroy');
    Route::get('/roles-permissions', [RolePermissionController::class, 'index'])->name('roles-permissions');
    Route::post('/roles', [RolePermissionController::class, 'storeRole'])->name('roles.store');
    Route::put('/roles/{role}', [RolePermissionController::class, 'updateRole'])->name('roles.update');
    Route::delete('/roles/{role}', [RolePermissionController::class, 'destroyRole'])->name('roles.destroy');
    Route::post('/permissions', [RolePermissionController::class, 'storePermission'])->name('permissions.store');
    Route::put('/permissions/{permission}', [RolePermissionController::class, 'updatePermission'])->name('permissions.update');
    Route::delete('/permissions/{permission}', [RolePermissionController::class, 'destroyPermission'])->name('permissions.destroy');
    Route::get('/settings', [SchoolSettingController::class, 'index'])->name('settings');
    Route::put('/settings/{group}', [SchoolSettingController::class, 'update'])->name('settings.update');
});

require __DIR__.'/settings.php';
